# Generated by Django 5.2.2 on 2025-10-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hints', '0002_problem_problem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
