# Generated by Django 5.2.14 on 2026-05-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hints', '0003_problem_topic_alter_problem_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
