# Generated by Django 5.2 on 2026-05-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hints', '0004_alter_problem_problem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hintdelivery',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hintdelivery',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
