# Generated by Django 5.2 on 2026-06-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hints', '0005_hintdelivery_feedback_hintdelivery_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='execution_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='language',
            field=models.CharField(default='javascript', max_length=50),
        ),
    ]
