# Generated by Django 5.2 on 2026-06-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hints', '0006_attempt_execution_time_attempt_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='hints_requested',
            field=models.IntegerField(default=0),
        ),
    ]
