# Generated by Django 5.2 on 2026-07-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hints', '0009_userprofile_current_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='user_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hintdelivery',
            name='user_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
